/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html"],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#3a494b",
        "primary": "#00f2ff",
        "on-secondary-fixed-variant": "#45455b",
        "surface-container-highest": "#34343d",
        "on-primary-fixed-variant": "#004f54",
        "inverse-surface": "#e4e1ed",
        "secondary-fixed": "#e2e0fc",
        "surface-container-high": "#292932",
        "error-container": "#93000a",
        "on-secondary-container": "#b8b6d0",
        "tertiary-fixed": "#e9ddff",
        "tertiary": "#fcf5ff",
        "on-tertiary-fixed": "#23005b",
        "secondary": "#c6c4df",
        "primary-fixed-dim": "#00dbe7",
        "surface-bright": "#393842",
        "tertiary-fixed-dim": "#d1bcff",
        "inverse-primary": "#00696f",
        "on-primary-fixed": "#002022",
        "on-tertiary-container": "#7318ff",
        "on-surface-variant": "#b9cacb",
        "surface-container-low": "#1b1b23",
        "background": "#13131b",
        "surface-container-lowest": "#0d0d16",
        "on-error": "#690005",
        "on-background": "#e4e1ed",
        "inverse-on-surface": "#302f39",
        "on-error-container": "#ffdad6",
        "surface-container": "#1f1f27",
        "on-surface": "#e4e1ed",
        "on-tertiary-fixed-variant": "#5700c9",
        "on-tertiary": "#3c0090",
        "primary-container": "#00f2ff",
        "surface": "#13131b",
        "secondary-fixed-dim": "#c6c4df",
        "surface-dim": "#13131b",
        "error": "#ffb4ab",
        "outline": "#849495",
        "on-primary-container": "#006a71",
        "tertiary-container": "#e3d4ff",
        "secondary-container": "#47475d",
        "on-secondary": "#2f2e43",
        "on-primary": "#00363a",
        "primary-fixed": "#74f5ff",
        "on-secondary-fixed": "#1a1a2e",
        "surface-variant": "#34343d",
        "surface-tint": "#00dbe7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "64px",
        "container-max": "1200px",
        "unit": "8px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Montserrat"],
        "display-lg": ["Montserrat"],
        "headline-lg": ["Montserrat"],
        "label-md": ["Inter"],
        "mono-data": ["JetBrains Mono"],
        "headline-lg-mobile": ["Montserrat"]
      }
    },
  },
  plugins: [],
}